/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: shared_lib.i

package shared_lib


/*
#cgo CFLAGS: -I.
#cgo LDFLAGS: -L. -L./shared_lib -ltest
*/
/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_shared_lib_7e3a9065620707d0(uintptr_t arg1);
extern uintptr_t _wrap_new_TestClass_shared_lib_7e3a9065620707d0(void);
extern void _wrap_delete_TestClass_shared_lib_7e3a9065620707d0(uintptr_t arg1);
extern void _wrap_TestClass_test_shared_lib_7e3a9065620707d0(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_shared_lib_7e3a9065620707d0(C.uintptr_t(_swig_i_0))
}

type SwigcptrTestClass uintptr

func (p SwigcptrTestClass) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTestClass) SwigIsTestClass() {
}

func NewTestClass() (_swig_ret TestClass) {
	var swig_r TestClass
	swig_r = (TestClass)(SwigcptrTestClass(C._wrap_new_TestClass_shared_lib_7e3a9065620707d0()))
	return swig_r
}

func DeleteTestClass(arg1 TestClass) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_TestClass_shared_lib_7e3a9065620707d0(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrTestClass) Test() {
	_swig_i_0 := arg1
	C._wrap_TestClass_test_shared_lib_7e3a9065620707d0(C.uintptr_t(_swig_i_0))
}

type TestClass interface {
	Swigcptr() uintptr
	SwigIsTestClass()
	Test()
}


